# Generated by Django 5.0.3 on 2024-03-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentverification',
            old_name='seller_name',
            new_name='sellername',
        ),
    ]
