# Generated by Django 5.0.3 on 2024-03-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification_app', '0002_rename_seller_name_documentverification_sellername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
