# Generated by Django 5.0.3 on 2024-03-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification_app', '0003_alter_documentverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=10),
        ),
    ]
