# Generated by Django 5.0.3 on 2024-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification_app', '0004_alter_documentverification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationDB',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sellername', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('role', models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentVerification',
        ),
    ]
