# Generated by Django 5.0.3 on 2024-03-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification_app', '0005_documentverificationdb_delete_documentverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverificationdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
